import { StyleSheet } from "react-native";
import { Dimensions } from "react-native";
import { COLOR } from "../../src/values/color/color";

export const styles = StyleSheet.create({
  // CONTAINER DEFAULT STYLE
  container: {
    backgroundColor: COLOR.PRIMARY,
    flexDirection: "column",
    flex: 1,
    top: "3%",
  },
  alertDanger: {
    position: "absolute",
    top: "0%",
    backgroundColor: COLOR.DANGER,
    width: "100%",
    padding: 0,
    height: "0%",
    justifyContent: "center",
    alignItems: "center",
  },
  alertSuccess: {
    position: "absolute",
    top: 0,
    zIndex: 100,
    backgroundColor: COLOR.SUCCESS,
    width: "100%",
    padding: 0,
    height: "0%",
    justifyContent: "center",
    alignItems: "center",
  },
  container_horizontal: {
    flexDirection: "row",
    flex: 1,
    justifyContent: "space-evenly",
    flexWrap: "wrap",
    rowGap: 50,
    marginBottom: "20%",
  },
  header: {
    flex: 1.5,
    paddingTop: "20%",
  },
  form: {
    width: "80%",
    flex: 4,
    justifyContent: "center",
    alignSelf: "center",
    color: COLOR.WHITE,
  },
  tableauWorkingTimes: {
    width: "90%",
    alignSelf: "center",
    flex: 4,
    color: COLOR.PRIMARY,
  },
  bandeau: {
    width: "100%",
    backgroundColor: COLOR.SAND,
    height: 45,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLOR.SECONDARY,
    flexDirection: "row",
    paddingLeft: 10,
    color: COLOR.PRIMARY,
  },
  tableau: {
    width: "100%",
    height: 45,
    borderWidth: 1,
    borderColor: COLOR.SECONDARY,
    flexDirection: "row",
    paddingLeft: 10,
    justifyContent: "center",
    alignItems: "center",
    color: COLOR.PRIMARY,
  },
  clocks: {
    width: "80%",
    flex: 4,
    justifyContent: "center",
    alignSelf: "center",
  },
  input: {
    width: "100%",
    marginBottom: 25,
    color: COLOR.WHITE,
    placeholderTextColor: COLOR.WHITE,
  },
  button_bottom: {
    flex: 1,
    alignSelf: "center",
  },
  loader: {
    flex: 1,
    alignSelf: "center",
  },
  Title: {
    color: "#ffffff",
    // font size responsive
    fontSize: Dimensions.get("window").width * 0.09,
    fontWeight: "bold",
    // top: 100,
    textAlign: "center",
  },
  ButtonSubmit: {
    width: 150,
    height: 50,
    borderRadius: 15,
    marginBottom: "5%",
    padding: 15,
    textAlign: "center",
    backgroundColor: COLOR.SECONDARY,
    color: COLOR.SAND,
  },
  position: {
    alignSelf: "flex-end",
    paddingTop: 32,
    paddingBottom: 32,
    paddingLeft: 32,
  },
  Register: {
    color: COLOR.WHITE,
  },
  ButtonClocks: {
    width: 150,
    height: 50,
    borderRadius: 15,
    padding: 15,
    textAlign: "center",
    justifyContent: "center",
    alignSelf: "center",
    alignItems: "center",
    backgroundColor: COLOR.PRIMARY,
    color: COLOR.SAND,
  },
  clocks: {
    width: "60%",
    flex: 2,
    alignSelf: "center",
  },
});
