export const COLOR = {
  PRIMARY: "#171A21", //BACKGROUND COLOR
  SECONDARY: "#2B3241", // SECONDARY COLOR
  SAND: "#D7BA8B", // GOLDEN COLOR
  LOGOUT: "#FF0000", // RED COLOR
  INACTIVE: "#929292", // INACTIVE COLOR
  WHITE: "#ffffff", // BASIC WHITE COLOR
  DANGER: "#f8d7da", // RED COLOR
  SUCCESS: "#d4edda", // GREEN COLOR
};
